apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: keycloak-postgres-db
  namespace: keycloak
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: postgresql
      componentDef: postgresql-12
      enabledLogs:
        - running
      disableExporter: true
      affinity:
        podAntiAffinity: Preferred
        topologyKeys:
          - kubernetes.io/hostname
        tenancy: SharedNode
      tolerations:
        - key: kb-data
          operator: Equal
          value: 'true'
          effect: NoSchedule
      replicas: 2
      resources:
        limits:
          cpu: '0.5'
          memory: 0.5Gi
        requests:
          cpu: '0.5'
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
