---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: default
spec:
  encryptedData:
    github_token: AgCE3pqpFqHfHtCkVkzcRthxdOshXTP7Hvqf2vJpYeIS25Z9gou6eG27bS2gWtSH7icF3DD14EyimlOBNDza2kzoliRZHQxjJr4R1QX8RJxR4DyRo70m6jQ14U0h9ga9obWaLHoM/g/XshDFxtrrQ5qQpbPk1as5OBrsQVRcfgVuYxugfhfMEfMoXR3pGKp7DoZjutEt5hqTgnpRhSJlpAzotRQ2+YK7PuQpkNd9lRG07b2MWL4jhuzkMLLsQ5vlS1XSvVbjAZHIzuViE2sla3hTZdg9RmGoCo7+HEvb+bDuTDUrg4QfPatiS5L2In7gEhK/XpOwJ2FC0nEgA8uMH4bLlBJCoYm+PtUIUs1RhsVvY7hxH45i66wFctk0wFP6bWRRSnEgyNUzZVnmsqZ3kZS60JmnRi9hd3RatReCBZhAWqkQKe7sZFrxzKsXlXWXDj3w3HZ/8WXxFI0G2mhWEMwlzX6429Z/K3B8S9lOGaPvteA2z2zhXhr41A0i9SuLkUD3E7B9TC5UgBzolLNz4nJqMXDsbI/Yj2eCCO2ZpT1K4+mTRNZaX6MnVsafUNtMPEvSio0M59M+S1qO50feu1/Pkm8XZ/OjIGDxbGneSxh96vuD6TCgS0/Qhh+M4AnX38IBrSjY+4UVWXywkZaiaD/mUM01lIEzSexBRZUlkmS0wjji/0QV7JIY5zGVO4TP8t+tmX/JZ3luXsnIE/78kxI9fCBR6puY1bmxr/l4dBE8OQrvpLMK5/t/nPOpwbr/Pk56unJj2WeLAQ==
  template:
    metadata:
      creationTimestamp: null
      name: github-pat
      namespace: default
