apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeblocks-snapshot-controller
spec:
  project: default
  source:
    repoURL: https://piraeus.io/helm-charts/
    chart: snapshot-controller
    targetRevision: 4.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeblocks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeblocks-crds
spec:
  project: default
  source:
    repoURL: https://github.com/apecloud/kubeblocks
    targetRevision: HEAD
    path: 'releases/download/v0.9.2/kubeblocks_crds.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeblocks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeblocks
spec:
  project: default
  source:
    repoURL: https://apecloud.github.io/helm-charts
    targetRevision: 0.9.2
    chart: kubeblocks
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeblocks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
