apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  project: default
  sources:
    - repoURL: 'https://charts.longhorn.io'
      targetRevision: 1.8.0
      chart: longhorn
      syncPolicy:
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        automated:
          prune: false
          selfHeal: false
