---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAfKKqjr3mOszaRRCV33dVDX2J134TW/ll2+CH4bD8jFrSe0v1yEs5vqqCSZo+GcViOVgezpKJZSlCPoZWXXTxHuz2SC+6+902mDl2Fm6Rz7wUM9XEVJ2NnRl1YYULEPLAh2IupWwRHUrETnxsvKTYMd49CDtzPknJQDvLTiC4BEsoDHJgwTANkA5ZCgJyxMHtMI33fXtzoh2bGcIzjxROszm12NxQC3eSfuf/kIyU3gJNrXZ5HltuTy3uGE7gTPLPV6FQRZS1l5uOU698p8fRc5FjRqo0PKHRiftoViHCW8nB6jS8Atn9zdS26XZCPSmSEBUj35zaymGHw6pueSo2knL76/mWolA3l81uoQiDLQEo2kTJinzAOLvxvb5vYTr+f57IjaqLIZUkFo4XQpzsMJeSiI5bbqe+B8vPwNpi3aL45WTcCz3jkgJfxqqFPan69Er7hbC7pbhShuOqrMFzAfTII4k6kphSubQXn3mp5Px05TyC0HkxzpWnBZ7y110rBOFHQmG9mvHz3RcgNrI+tgqQANWbgTlRJxPAcwclo4UvSdLHjBDf62E3/QtR33zbSb7jeueSUit0KDTHqZx3xUlKystV9z+m6wkiDgLZ1Ra5cR7U21Bd9e2nVtRzAbNloKcMUBwIR0LQrRTlFtOYkohH3kKYRnSmOt6ARAGNbu0TJ7dxV7/pPL0dfdpbDLy5awlyZxFeu13U8+FjtxYKY3CNqJ79NC8qSkjr8Pwp+3WT8nq8/6c78
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
