---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgB9JO64d/A75tyJwgZIEQX/OJNrBWvuUgBdOd3muw+sTOowjI7cichcgdvtmQ6zGHWwOhF4laSoV+3Vp/FCDPPhkWpoLYyEvld5/EwtxhlrLW4o1nq07r99TcP2z4BaHt1ik3fPolIOFqGnG/gb0JqkeNwb3dlcpwgx7zXiBzTFq9fPqxGCtfwGwefya6RrH+D97Qx48GSdlFeqxceInEWStUz7hu6zUsIIFuMx/l9XojBhxksScacA18krmVcJSGYJL+FC/eMlP2eeWDtq1/bvLbQl9w6KMxaI5Fn31KEtOXGUw+sxYiY9pabANp7tMhs07t5G0PPT+U+uhhXoH3oBJk0s1V5E0EvcxFD/6PVMF9QjcCGdLoKKYXzVxnIMrk7lP8rAQdVPbTrER9Jv8TfZesqjYv7byii/jf8Kq8H3TpiLzRyIDnTYZbI3o30xQckIc4gusEb5QY/4d5waa9y8VtlVYcx2WZiAlFunPSM5mgco8a9dc7emm/Loc6uiTmI/exU5/eB0oEJ3ERqtZieuQ6TOGftllynO3hSl+BaImIHp+wEJUkekunUshYRs/j69K30jTlocaeowWEcweUZB5//n7XAsigJub73Cerucd+lFsO3p+utbaLHw/cigRqTEuV80lJ/8eNItl9+6r9teuCDGFq0mL36y4YXlcndYPGpNqxjoXYWFrrB9TubQvooKo69eROEU13jYw7uwNcBVz5pbSWBr/CKExn8Tu0o8FAgTTepstOx1
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
