---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCafdRxjkWeSXMqV025O+fS1ute0YXJiwzPKiNxiT7OC/sle+bg6FJQm39MiEJFoT2b6Roy+NPqDRn9IG3IiI+TROLykwiIMaOJ7ZHrLsO/iGFP8Ndv4GVC4RT/OfS7pZGlx1a0PZprmGqkhfEkwk9vytFPBJpdG2csGmK2c+tsDXxcR5IwZsE4vOvkHcT5EG/k9c/ljzYyn5iX02O2yNYNlwxyIyxQ/Fudp3Oh7dWna1NlEXtp4wZXIQOCS13QJFUjsX87j1jiLmQtZJfPUklbaUsTtjmS/ynygMIOrO0SEWSGuFj5ftzb6sntngYtDEIaHxGKRftt6oJZbRf1H3dFYc/6Tm/MH0Deg8QbiOeqInKKdQsgVYqKjDboRjrHA69V2+4AAwxHdulBClQtfUpNpYMEfR39IUPV1ePyqxQrfMPfDi6pfCO7L0HgCPrSvdhPSpj/pgBxEBOn5zSmKcG3stXhyFfs0kBAFXYKx0RUzlDq/o5MZLcYHrzmEae0IDaORH/H+6LTAjy0is/dgT4h1PEBz0J/4MWqLxG/nPl3AhVZZ0BHDQ+gVlKfcMN1Od9+n8oxQ3VjGkX4vW9RZmuJTHb1ZRqdUS5zDLKrvujaBwwZ7o3wqPNXRS8JO9UDjFGlwdOtjsR6MG5AKQEmqhk5DOHqtvDrfPg2q0WglUNyH7UW0n+h1InZnX9yfrQziEJFtdAifOV0F3oFHsfpVtvpOoYKvLocZ124bAYVf8NFud4ZUiLQksgM
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
