---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAGsZlfR9QRbCnEk9TxJzl9kqDFpY0/N87BRjncmWxWv8XCBZ+ggJNOGicH7oHVpcLkM+K6CV0tBDGVIa06Tesln4kHhVWz0BmTRNirJ1zhcq9oG1VH6T6QgcRbX+RjVywwZHKeyf40hUvVliyaaGfpzEXW6q+VoKcIXx7YmEiBbhQRX1ZwUFGtjYGHZxMl2Obsu4xzsUdASPn/px6oj672zcpOLEAmO/gXXPaOQugpvO2Bb3LLPbwmShiWxHmuF2ry10MBr8noYpZIXM7BivuoFz8jc/9ZDqkvd4thkvjQp0xrAilivfiv51Hu4E61hRIQZuwts8GMtTtEue4dNv0gTIrGzon5zJ68087eSYotrhnY9XsZC0mi2BUKOxgyPzQuTsaBCnhD3++Q+mrdqh1jtJckn0DFaZ+B/9grn69fgnbFgyhKK1TBGrV1g98HeOxPyY0jUlygKVqAC1MQvlhPRXG8ZRIViwMjIf1itfNL1YOJShY4IiJkVTxqJ7j4uf9nGdoFUv0108WyjvJ+JOZn3e1lZ3qBDjEtSPH2mKoFjXuijpzBs61gOOqR+rDlSMRJoOprZlaJMZCe2JTnh/baBTwX9ROcEWtx6fppvbMkdElQDwm2k+yMDSezvAckKtTqEOlHnfS4FMRoJghsS2sfBKKRC2X2E93TS4+UQq0hlZLJNB9NtT7Qw8cCDGl2/L2AFGhFt6HLeBmQCa5FoJRWOHrz0FGq2Ml70Zax+qCPs9thM4P8o5mw2Q==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
