---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-pat
  namespace: default
spec:
  encryptedData:
    cloudflare-token: AgDTA0sWB3LOvxzKMElPBnlhA7p7tT5UavFZff8bqzJRUGsf/DHh2teChkBNq5RH44w2NZ91Dm4FckFAZBI4vKDhc3kpIIw6g6zYOH+6AnxB+9e+OHWH9BYCP1yh3CevMGUMU/5qn9mn0PzwNGYvk+X9cu9qDpSGm+i8f7rjs5PFrJhjtE7sTxNXzttX1Hy5vbNzanc5Nn7k8pqLg/R3nvSkKHUlMI7G2m+N6xtUe/a/Q34YkpBBoFXby+4wcyy8OwiOPGum0svbjldX/jUXVbJ/YSyGKKpZCXhEqi5aIS6xXAoVtAw63wQTVd+WVSRRY4YE8+KPVuLCw695sZL70esuP1XdV38AoG3Xwi52CURCizo6cfse6TrnAqaNmPtZNi61sY1wImnQ7mIXKEE8TAavv3IfwHsle9EKD47Dj14A/u4dAiUsiLt+k6wi8LrIjrdczy6Kl4qxosM6GjAjqxECP9ESRFx+kf3YxUTJyOXAM1GrwagjBr0OIRG7dZFsrgsSNmSkXk3sEPoBzlFlvF+5+bWnEIS6YUvmimbVQl2Jsi46zkHSsR8eN1zaHwz9Z/x13MCINSEpmcTg4Ats/S+vReKdwXfapruaxnM2XpTDMzDG/EQRh2snEPYw9Jk+I2io9DdMrvDZbIva9tI9it8EY0GMbmzMBSBnW+wbnOLDpJMb3f9UgHNrWv64G2xeagZZmOoF4XtzL75PXEYeHuzfwt2DxqWW9iZDyJLQBzc139elB1SOFPZF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-pat
      namespace: default
