---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAK+Au29fZS29HdJmJtV2y5VZ0atKdG1dKh7u1ukLsckHreKPYinZSIgmYM3+hGS3EkIyLt0mI6mJS1l+UPibnY5ieHnjAb/OgIZ+/tLukXQOUTeiSreH+ZHIHaGxVvBc9ZcyyMJNqzZNDTQRwoIZRL71/R8iw/avoaYENezugBAUimx6/D3m6J444nog/juAn0PURmYtuQNI0P7FDH7CMkmvJqJdGA6lUyAsYuqY6sTenY8P8Kwrni6SjLxo8f5GcWXV2M0pyDLI0ouL4G63gnk3Z+vBow2jjdBu8il9d9Ve/4WzYD8aMJ3qdHCDdp3AUMwXdfxHh5KKQaWz75Wh5VUdA5UWWdPS0dXK+LVRkyXm7mi5jqufNwdoPgyMVicKb50jLKUh9KchkEnQqtJceyKDYHy0lc56zCS5I9zcljH7GEntBxjOmWmWOz0qO7MRk0SWY2nEbgxBgyUMwYjQXkSNaoly2mGxEDqNJau4bqC9FSjbVZYcktH64uEhLsYzLgya7rE1SjbeQmAM8fmOFegrYaC8B4Enz2zq/Liy4pyTZ6Hr+r7MZO4OkaiyPTSuO6bga85+An2dHOEMbdTFhMyQ8nglFUUsNjAy23XNHr1yvNKAtcToUcO0Tot6trZBs7J5Bhk4rOgvNafZaY1wPLfKs6DyFA15rrV0L8hMQ41WnhW24Q3Q9+u+SlwrQcNiuhJDOSdUFiSsof/6/ZSHB4hmDagCqB/3lmQ1gdZV2aHaI6iq33CnsP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: default
