apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-001083-xyz-tls-prod
  namespace: cert-manager
spec:
  secretName: local-001083-xyz-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.local.001083.xyz"
  dnsNames:
    - "local.001083.xyz"
    - "*.local.001083.xyz"
