apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: andrewpaulcichewicz@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: andrewpaulcichewicz@gmail.com
            apiTokenSecretRef:
              name: cloudflare-pat
              key: cloudflare-token
        selector:
          dnsZones:
            - "001083.xyz"
