apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-001083-xyz-dev
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "authentik, monitoring"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  secretName: local-001083-xyz-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.001083.xyz"
  dnsNames:
    - "local.001083.xyz"
    - "*.local.001083.xyz"
