apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-example-com
  namespace: traefik
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "*"
  secretName: local-001083-xyz-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.001083.xyz"
  dnsNames:
    - "local.001083.xyz"
    - "*.local.001083.xyz"
