---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBSlzn4PiOxt6Wkj5HmeHRJiU7MDIppiJmwCbGacLYUBm5wWMCrPYs+noE0DiIh9UY6+NB3Yfol8TvYlEcm4AVlCKNh491Y8DDv1Fih+Q253WiR8eL1lTxlYvw7ZC3dPr3m+QH8ubqZnLBMNYULebArB2H9YL+HohQKYgOVvU+UIDdGZarjL7i/b4h2xzwLLseVVDmexUFPs/uYN5LbpT3UadlQNUL6yfwDSlgklVRBVD42flVF9bKOphxub6B7SYzaKgVrLLqceDCTCy0zdE4ohY/+b/t/xvQ9tRHZzBvpE7JncVOR035pYkNPgdaRCBHuXp6hNasgzsYu08EM3yJOSSgNTUt0+G/JR87Vbt+gdDWydR5TBE6v5JHa67Gdz2Pj1YmmCKUT650eMJK3yKmMh+kOyrqrn4faQ59PZyQYWQia3B3eYtHPTKpJLN+Q9zx/MFDu15gEA88OUPPXJ2Z7APG9CpXMWowOxIxytVpE5O44xev6HfWhSzgnKe62aiSN7/tPyzVGcU/ku1mpzWSup3L9yu0PpQjnb9XMVso9Zr86tsmHR5udWeEwt7GQrYJZBxs2I6cG6bH25+g3RidlxCqMW3KHKXxb5oTRkHNwjBCZmPfFuoyxi3AJTEkNlzWT8QybMYUWtYrPlClK/1HyTdC1DL6imBqrUV0acnrKrFY9Bg67FDnF9mg26IqZ2/tRhVtojYyBAuXP7bcxZhlNHEesUVbe+QNyfk8dj/CeI5qh72xeA80Z7Q==
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system
    type: Secrets
