apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default  
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 32.1.0
    chart: traefik
  sources:
    - repoURL: git@github.com:APCichewicz/cluster.git
      path: argocd/app_of_apps/network/traefik_values.yaml
      targetRevision: HEAD
  
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
