apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default  
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 32.1.0
      chart: traefik
      helm:
      valueFiles:
        - $repo/argocd/network/traefik_values.yaml
    - repoURL: git@github.com:APCichewicz/cluster.git
      targetRevision: HEAD
      ref: repo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
