apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keycloak.local.001083.xyz`)
      kind: Rule
      services:
        - name: keycloak
          namespace: keycloak
          kind: Service
          port: 443
  tls:
    secretName: local-001083-xyz-tls-prod
