apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: null
  name: authentik-redis
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  affinity:
    podAntiAffinity: Preferred
    tenancy: SharedNode
  clusterDefinitionRef: redis
  clusterVersionRef: redis-7.2.4
  componentSpecs:
    - componentDefRef: redis
      disableExporter: true
      enabledLogs:
        - running
      name: redis
      replicas: 2
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
      serviceAccountName: kb-authentik-redis
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
    - componentDefRef: redis-twemproxy
      disableExporter: true
      name: redis-twemproxy
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
      serviceAccountName: kb-authentik-redis
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
    - componentDefRef: redis-sentinel
      disableExporter: true
      name: redis-sentinel
      replicas: 3
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
      serviceAccountName: kb-authentik-redis
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
  resources:
    cpu: "0"
    memory: "0"
  storage:
    size: "0"
  terminationPolicy: Delete
status: {}
