apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-postgres-config
  namespace: authentik
data:
  pg_hba.conf: |-
    # Add custom rule for Authentik pods
    host all postgres 10.42.0.0/16 md5
