apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4K # username: user
  password: cGFzc3dvcmQ= # password: password