apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  destination:
    namespace: auth
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  - repoURL: 'https://charts.goauthentik.io'
    targetRevision: 2025.2.1
    chart: authentik
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
      valueFiles:
      - $values/values/values_authentik.yaml
  - repoURL: 'https://github.com/plpetkov-tech/argo_homelab'
    # Values from Git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    syncOptions:
    - Validate=false
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    automated:
      prune: true 
      selfHeal: true
