apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyter-gpu
  namespace: llm
spec:
  serviceName: jupyter-gpu
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-gpu
  template:
    metadata:
      labels:
        app: jupyter-gpu
    spec:
      runtimeClassName: nvidia
      securityContext:
        fsGroup: 1000
      containers:
      - name: jupyter
        image: cschranz/gpu-jupyter:v1.7_cuda-12.2_ubuntu-22.04 
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: "all"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility,graphics"
          - name: DEBIAN_FRONTEND
            value: "noninteractive"
        ports:
        - containerPort: 8888
          name: http
        resources:
          limits:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - name: jupyter-data
          mountPath: /home/jovyan/work 
  volumeClaimTemplates:
  - metadata:
      name: jupyter-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: jupyter-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 150Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-gpu
  namespace: llm
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  - port: 7865
    targetPort: 7865
    name: http2
    protocol: TCP
  selector:
    app: jupyter-gpu
---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jupyter-gpu
  namespace: llm
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jupyter.dunde.live`)
      kind: Rule
      services:
        - name: jupyter-gpu
          port: 8888
      middlewares:
        - name: default-headers
          namespace: llm
  tls:
    secretName: dunde-live-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: foocus-jupyter-gpu
  namespace: llm
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fooocus.dunde.live`)
      kind: Rule
      services:
        - name: jupyter-gpu
          port: 7865
      middlewares:
        # gets created for you from the outpost (if its called like that)
        - name: ak-outpost-auth-endpoint
          namespace: auth
        - name: default-headers
          namespace: llm
  tls:
    secretName: dunde-live-tls
