---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-creds
  namespace: auth
spec:
  encryptedData:
    secret_key: AgCtDX3gNYYp4zeIOPFPUPlH9JiozHfDO41JHHd6MHuabpL0B1fOZE4/elmlnpa05gR0QWro3/u4Fb3IvztqWN9uPzQSm+yyaYldF7kNQMKAEWyAh5MOwkgBXkl0P+dpIAy9TXPSNoiCeIMgWjoF531Bemnu5kcQjg4f8xD7JHZ8F9erC0oQ0SCb8ExneY+z7eScDPnm9AdBISxsGb3yZ33sdNwkz1pnfqsNx1dEYzVpymLwS0W/orPoDMypvN/uAZ0agHDmRagOkoAcs7Fi1MNj1dYZojQOj4POATcH2MEDYa6gNy+k7OdQLew5RN9+pdH45c+EHk6lFz39qGh6+gKdf+l8zRdlgdwd7QAJTO13TmHtKwbZ+f+Zgh6E0LXvM7zwWBasuW9/cvXFjHe/Jo6WlR/4GE1Qb9yUXbfmcwnLS3Isb+L/SZpYB52kxLHFbNFsgckbYFgc5KseemF7XnlOzdlU9+4LmBkIjT1q2up0BDGOuBWgRrP13X7YwjcHx1t/t33tdUeTXnhE+RCLiExg/SclZjRxANbIG+jwpCUfwPN/I/sWc801UrggesT2K55DJJe97fvapxFJ19dHz/PvbrNrcaXNhLk9meLhHAExPnWDMVpjFFNwZ+1hxh3RMS7KxFTbQwMsLGPx+xDnS9GXJqjPLNGdunD4PFUb0VN9j9Z93SVYw2bm8+2tWkbRMXWp17gMLwCsJ4mv/V2EZ+CSKyUsjBfERRjouz9PhJm6sHvQXPZYCruPVXyNft5qSOEl7A==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-creds
      namespace: auth
