apiVersion: v1
data:
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  url: https://argocd.dunde.live
  dex.config: |
      connectors:
      - config:
          issuer: https://auth.dunde.live/application/o/argocd/
          clientID: d408b314019808a4bc1b767886205398 
          clientSecret: 787d539a1875f1d6e6e25445a7104c54 
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
        name: authentik
        type: oidc
        id: authentik
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
