apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring   
  project: default
  # Helm-specific source configuration
  sources:
    - repoURL: 'https://github.com/APCichewicz/cluster.git'
      path: argocd/app_of_apps/monitoring/values/alloy-values.yaml
      ref: values

      
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 5.5.0
      chart: alloy # Path to your Helm chart in the repo
      helm:
        # Release name (optional - defaults to application name)
        releaseName: alloy

        # Values file overrides
        valueFiles:
          - $values

      # Sync policy
      syncPolicy:
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        automated:
          prune: false
          selfHeal: false
