apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: grafana-postgres-db
  namespace: monitoring
spec:
  terminationPolicy: Delete
  clusterDefinitionRef: postgresql
  componentSpecs:
    - name: postgresql
      serviceVersion: "14.7.2"
      disableExporter: false
      labels:
        # Note: DO NOT REMOVE THIS LABEL
        apps.kubeblocks.postgres.patroni/scope: grafana-postgres-db-postgresql
      replicas: 2
      resources:
        limits:
          cpu: "0.5"
          memory: "0.5Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: ""
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
