---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgAkj7SpfFya25IJiXhvspiMMeusX9LgE8m378UWAg/DWU9LizHTa+P+iof5c8dxgzTGn40LAEDT92keskudQ7FZLeUqqRaNGIG2cMRTVo9yUC52nHxmgQ9O6cvx3JYBLF2p/5SmccngsFzIukIlROAbDj8STJBnRoaQqnEBJMiNPQrYzMvLRtjm/o0jU4DREiEo2BTOZOqZthlimk7S2bYvHywe/neK8XwF01MfVQFxm6mpq1r3vu9yAUzEhv+qQSvjnSPT9Yuus/sCI81wQZ5lNQFPeG7IeL1iTARQyzuvgY2OCZMi9wnSPzdEz6nLFGrfOyfFWTMK3w/WW0uWaZtyEADKLGU4qkv4402cSHg3QuM1ymhoI88zs4qWzPSf/UCZXlYWtZfISZ1w41REq+CZ9ZPFmd33uJgqEoakjhpLJolkfbkbQZRJa16wnkfiPM7qClD4zAOwf3t2id8Vl6d6VoQwVYGhfiJi2qypVgDpo840saOuXw8OvMvOB9hJR48CEpHq6ztOPIKKer/Q3CiUG8tic+Bwb6ast0Kbs1jxMXz93Hq7ehviy8hlHsNPSADTFifObulfApNJ6lr22ugTvGgzL0SdbOejtRoxyRI0tA0IxKJFXdfTS7/atiaMBCR1OZJlA6mzwjRXX/jzN72vQ6QXKuVwGXjejIWeciYTMnnCoDmI3hjwnDZLO/+rcapagxR8qamO2VbGS2wudNG4Pf7roQreq4F5IOOjAnsj8mYadfAf2aSi
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCzh6RxoFrAkCNdYScOUp2OF2X+zlOYhXRtABVYwEWhqfYHB7PooIeA93X6LtPkmWwmnntle2oYQIRkk/KXbynaV2Cwa8bl0VNHZZIb0lAU2NUJyia3IjaMTgXXKB8ipFukgolOTkpsgbMSTAqNCeXVHYTEpIW0S4tPmq/6kLQ3Uy8+nmp0JJm7Shxa2e6i6rRV2KGfOWwFy8zpeOZhNV0kmEtwgJD0FRb2bbQF54LCL36TuCcKeh58iD6Wo4D71s9NJIoQ6P/D3Yam1bETduo41mCu3E2n0+lNQbMhl+eZoHL7ZY6Lx3ciHIgxXcDrLcZ/xacL0yVwpkX7TidHhaITohLeCheLedD5RsPZPUcVs5akN7s/aYOXq7OymmoNWbUaGjoyvHvD1cs+2QwyFrK2KTclD/Bagh4BFm+ellIh/u2Vq4V1YQsN3t9Z4W4gQGqcJZn1yeVd3b7vGy4ImyeduPviS3/SY6bwLyYyq11dOZAaXkJkuoO+h3l/xZ9noGwdAlyUEzVNHTL/hY57jeyF5cwEXnwinqbUd3ANIxrf6xXvkkxE9UR7BapWkzhSwNsHLd16b0AXjs/wLU3yuyNao4ghXSnWaYDzKGrleCra0byQMeCg9AVXoPRtWy+eENOjhH/YXmovU7whf7ZIJtR6gXVyZZ7X0DguWJOn5KGnes1L1PssyTB5bECbjNis5EcA4/biAmUttvA99VpKFxeQzNNSOGBBUCNq6zNI0xm3Cdf3n0rE3V8u51YekdOTlbz9VoTZCM0D+j+C4EWxKfPR8ha2xEHCTM4M86H99xFIgJb8VXi+KEIh61xR/VID4ihLD4KoolkHeEt+/kYJtNQP05bJ01UOT+qqRhmUQuavng==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oauth-secret
      namespace: monitoring
