apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  # Helm-specific source configuration
  sources:
    - repoURL: 'https://github.com/APCichewicz/cluster.git'
      ref: values
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 8.6.1
      chart: grafana # Path to your Helm chart in the repo
      helm:
        releaseName: grafana
        valueFiles:
          - $values/argocd/app_of_apps/monitoring/values/grafana-values.yaml
    
      # Sync policy
      syncPolicy:
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        automated:
          prune: false
          selfHeal: false
