apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default

  # Helm-specific source configuration
  source:
    repoURL: https://grafana.github.io/helm-charts # Your Helm chart repository URL
    targetRevision: HEAD
    path: grafana/mimir-distributed # Path to your Helm chart in the repo
    helm:
      # Release name (optional - defaults to application name)
      releaseName: mimir

      # Values file overrides
      valueFiles:
        - values.yaml


  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true