apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 6.16.6
      chart: promtail
      helm:
        releaseName: promtail
        values: |
          config:
            # publish data to loki
              clients:
                - url: http://loki-gateway/loki/api/v1/push
                  tenant_id: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
